name: curved_app_bar
description: A lightweight and customizable curved AppBar widget for Flutter applications.
version: 1.0.6
homepage: https://github.com/labib-ur-rahman/curved_app_bar
repository: https://github.com/labib-ur-rahman/curved_app_bar
issue_tracker: https://github.com/labib-ur-rahman/curved_app_bar/issues

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - appbar
  - curved-appbar
  - flutter-ui

screenshots:
  - description: 'Shows a curved gradient app bar with drawer button and action menu.'
    path: screenshots/gradient-app-bar-with-tab.webp
  - description: 'Shows a solid color CurvedAppBar implementation.'
    path: assets/preview/Solid-Color-App-Bar.png
  - description: 'Shows a gradient CurvedAppBar implementation.'
    path: assets/preview/Gradient-App-Bar.png

flutter:
  assets:
    - assets/preview/
