name: curved_app_bar
description: A lightweight and customizable curved AppBar widget for Flutter applications.
version: 1.0.3
homepage: https://github.com/labib-ur-rahman/curved_app_bar
repository: https://github.com/labib-ur-rahman/curved_app_bar
issue_tracker: https://github.com/labib-ur-rahman/curved_app_bar/issues

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - appbar
  - curved-appbar
  - flutter-ui
